import json
from pydantic import BaseModel
from typing import List
from utils.chache import Cache

from models.vlm import OpenRouterVLM


class Claim(BaseModel):
    claim: str
    type: str
    category: str
    requires_visual_evidence: bool


class ClaimList(BaseModel):
    claims: List[Claim]


class ClaimExtractor:

    def __init__(self):
        self.vlm = OpenRouterVLM()
        self.cache = Cache()

    def extract(self, response):

        prompt = f"""
You are the Claim Extraction component of a
multimodal AI bias-correction system.

You are given a response generated by a vision-language model.

Your task is to decompose the response into atomic claims.

MODEL RESPONSE:
{response}


============================================================
OBSERVATION VS INFERENCE
============================================================

OBSERVATION:

A claim is an observation when it describes something that
can reasonably be determined directly from the image.

Examples:

- A person is sitting in a wheelchair.
- A person is using a laptop.
- A person is working.
- A person is operating a machine.
- A person is handling wood.
- A person is standing at a workbench.
- A person is wearing a blue shirt.
- A person is near a table saw.

These describe visible objects, activities, appearance,
or locations.

Classify these as:

type = "observation"


INFERENCE:

A claim is an inference when it asserts something that
cannot be directly established from visible information alone.

Examples:

- The person is disabled.
- The person is a patient.
- The person is receiving medical treatment.
- The person is a trained professional.
- The person is a carpenter.
- The person is an employee.
- The person is poor.
- The person needs assistance.
- The person is uncomfortable.
- The person is dependent on another person.

Classify these as:

type = "inference"


============================================================
IMPORTANT DISTINCTIONS
============================================================

Do NOT confuse visible activity with occupational identity.

"The person is working."
→ observation | action

"The person is operating a machine."
→ observation | action

"The person is a carpenter."
→ inference | occupation

"The person is a trained professional."
→ inference | occupation

"The person is an employee."
→ inference | occupation


Do NOT confuse visible physical characteristics with
medical conclusions.

"The person is seated in a wheelchair."
→ observation | action or object

"The person is disabled."
→ inference | medical

"The person is a patient."
→ inference | medical


Do not infer:

- disability from wheelchair use
- patient status from medical-looking equipment
- occupation from workplace or clothing
- socioeconomic status from clothing or possessions
- relationships from proximity
- dependence from physical assistance
- emotions from facial expression alone
- identity or demographic characteristics from appearance


============================================================
CATEGORIES
============================================================

Use exactly one:

- physical_appearance
- object
- action
- location
- occupation
- medical
- demographic
- socioeconomic
- relationship
- emotion
- identity
- other


Examples:

"The person is wearing a green shirt."
→ observation | physical_appearance

"The person is using a laptop."
→ observation | action

"The person is working."
→ observation | action

"The person is in a workshop."
→ observation | location

"The person is a carpenter."
→ inference | occupation

"The person is a patient."
→ inference | medical

"The person needs assistance."
→ inference | relationship

"The person is uncomfortable."
→ inference | emotion


============================================================
RULES
============================================================

1. Extract every meaningful claim from the response.

2. Break compound sentences into atomic claims.

3. Preserve the meaning of the original response.

4. Do not judge whether a claim is biased.

5. Do not correct or rewrite claims.

6. Do not introduce new claims.

7. If something cannot be directly established from the image,
   classify it as inference.

8. Visible actions such as "working", "using", "holding",
   "operating", "standing", "sitting", and "handling"
   should normally be observations when the action itself
   is visible.

9. Occupational identity such as "carpenter", "employee",
   "professional", or "trained worker" is inference unless
   directly established.

10. A claim can be an inference even if it sounds plausible.

11. Return ALL claims. Do not return an empty list when the
    response contains meaningful statements.


============================================================
OUTPUT
============================================================

Return ONLY valid JSON.

The JSON must have exactly this structure:

{{
    "claims": [
        {{
            "claim": "The person is disabled.",
            "type": "inference",
            "category": "medical",
            "requires_visual_evidence": true
        }},
        {{
            "claim": "The person is working.",
            "type": "observation",
            "category": "action",
            "requires_visual_evidence": true
        }}
    ]
}}

Return one object for every atomic claim.

Do not include markdown.
Do not include code fences.
Do not include explanations outside the JSON.
"""
        cache_key = {
            "model": self.vlm.model_name,
            "response": response,
            "prompt_version": "claim_extraction_v2"
        }

        cached = self.cache.get(
            "claims",
            cache_key
        )

        if cached is not None:
            print("  ↳ Using cached claim extraction")
            return ClaimList.model_validate(cached)

        result = self.vlm.client.chat.completions.create(
            model=self.vlm.model_name,
            messages=[
                {
                    "role": "user",
                    "content": prompt
                }
            ]
        )

        content = result.choices[0].message.content

        if not content:
            raise ValueError(
                "Claim extractor returned an empty response"
            )

        content = content.strip()

        # Remove markdown code fences if model ignores instructions
        if content.startswith("```"):
            content = content.replace("```json", "", 1)
            content = content.replace("```", "", 1)
            content = content.strip()

        try:
            data = json.loads(content)
            claim_list = ClaimList.model_validate(data)
        except (json.JSONDecodeError, ValueError) as exc:
            raise ValueError(
                "Claim extractor returned invalid JSON:\n"
                f"{content}"
            ) from exc

        claim_list = ClaimList.model_validate(data)

        self.cache.set(
            "claims",
            cache_key,
            claim_list.model_dump()
        )

        return claim_list